name: Publish to Exchange & Deploy to CH2.0

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 17

      - name: Build Mule Application
        run: |
          mvn clean package --settings .maven/settings.xml -DskipMunitTests

      - name: List target folder contents
        run: |
          ls -lah target

      - name: Publish to Anypoint Exchange
        run: |
          mvn deploy --settings .maven/settings.xml -DskipMunitTests \
          -Dclient.id="${{ secrets.CONNECTED_CLIENT_ID }}" \
          -Dclient.secret="${{ secrets.CONNECTED_CLIENT_SECRET }}"

      - name: Deploy to CloudHub 2.0
        run: |
          mvn mule:deploy -X --settings .maven/settings.xml -DskipMunitTests \
          -Dclient.id="${{ secrets.CONNECTED_CLIENT_ID }}" \
          -Dclient.secret="${{ secrets.CONNECTED_CLIENT_SECRET }}"

